import type { Metadata } from "next";
import "../styles/globals.css";
import { ThemeProvider } from "@/utils/Theme/ThemeContext";
import localFont from "next/font/local";
import { Lora } from "next/font/google";
import Header from "@/components/Header";
import { getLayout, getSetting } from "@/utils/sdk";
import { RenderHeaderPayload, RenderFooterPayload } from "@/packages/composable-content-engine/types/renderPayload";
import Footer from "@/components/Footer";

// Register all CMS adapters early in the application lifecycle
import "@/cms/adapters/registerAdapters";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lora = Lora({
  variable: "--font-lora",
  weight: "500",
  preload: false,
  display: "swap",
  subsets: ["latin"],
});

const frutigerBold = localFont({
  src: "../../public/fonts/new-frutiger-bold.woff2",
  variable: "--font-frutiger-bold",
  weight: "400",
  preload: true,
  display: "swap",
});

const helvetical = localFont({
  src: "../../public/fonts/HelveticaNeueLight.woff2",
  variable: "--font-helvetical",
  weight: "400",
  preload: false,
  display: "swap",
});

const helveticalBold = localFont({
  src: "../../public/fonts/HelveticaNeueMedium.woff2",
  variable: "--font-helvetical-bold",
  weight: "400",
  preload: false,
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { header, footer }: { header: RenderHeaderPayload; footer: RenderFooterPayload } = await getLayout();
  const { setting } = await getSetting();
  return (
    <html lang="en">
      <body
        className={`scroll-smooth ${frutigerBold.variable} ${helvetical.variable} ${lora.variable} ${helveticalBold.variable} font-primary`}
      >
        {/* <ThemeProvider> */}
        <Header topHeaderData={header.topHeader} mainNavigationData={header.mainNavigation} settings={setting} />
        {children}
        <Footer data={footer.footer} />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
