import type { Metadata } from "next";
import "@/generic-cms/src/styles/globals.css";
import { getServerContext } from "@remkoj/optimizely-cms-react/rsc";
import localFont from "next/font/local";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Lora } from "next/font/google";

export const metadata: Metadata = {
  title: "Optimizely CMS Boilerplate - Create Next App",
  description: "Generated by create next app for Optimizely CMS",
};

const lora = Lora({
  variable: "--font-lora",
  weight: "500",
  preload: false,
  display: "swap",
  subsets: ["latin"],
});

const frutigerBold = localFont({
  src: "../../public/fonts/new-frutiger-bold.woff2",
  variable: "--font-frutiger-bold",
  weight: "400",
  preload: true,
  display: "swap",
});

const helvetical = localFont({
  src: "../../public/fonts/HelveticaNeueLight.woff2",
  variable: "--font-helvetical",
  weight: "400",
  preload: false,
  display: "swap",
});

const helveticalBold = localFont({
  src: "../../public/fonts/HelveticaNeueMedium.woff2",
  variable: "--font-helvetical-bold",
  weight: "400",
  preload: false,
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { locale } = getServerContext();
  return (
    <html lang={locale ?? "en"}>
      {/* As design,Font default is Frutiger Bold, please use this font first */}
      <body
        className={`${frutigerBold.variable} ${helvetical.variable} ${lora.variable} ${helveticalBold.variable} font-primary overflow-x-hidden`}
      >
        <div className="flex min-h-screen flex-col">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
